### ISSUE TITLE
0.7.0 update

### ISSUE THREAD

**Issue by segersniels** [Didstopia/colony-survival-server#11]
The new update removed the `colonyserverdedicated.exe` file and made things a bit trickier to run. 

I’m not behind my computer right now but to fix this you should:
- copy over `steamclient.so` from `linux64/steamclient.so` to `~/.steam/sdk64/steamclient.so` after the update/installation of colony survival
- forward port `27004` instead of `27016`
- change `colonyserverdedicated.exe` in `server.sh` to `colonyserver.x86_64` without `mono`
- and possibly add the following parameters to the server command `colonyserver.x86_64 -batchmode -nographics ...`

**Comment by segersniels** [comment]
If needed I’ll make a PR.

**Comment by Dids** [comment]
Checking this now, thank you very much for the thorough report. :)

**Comment by Dids** [comment]
Just to update on the current status of this:
- Couldn't find any information about port change yet
- Shutdown (graceful and otherwise) also seems to be broken

**Comment by Dids** [comment]
Talking with the devs now, still applying a few more fixes and testing that everything works.

**Comment by Dids** [comment]
Turns out both the game and Steam ports changed (27004 for the game, 27005 for Steam), which I ended up fixing by overriding them in the startup arguments, and using the previous default ports instead, just so this is less of a hassle for existing users/servers to upgrade to.

Works now, so I'll push a new image and close this.
